name: Scheduled Deployment

on:
  schedule:
    # Runs at 12:00 UTC every 2 days
    - cron: '0 12 */2 * *'
  # Manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # This step refreshes GitHub Pages by making a harmless change
      - name: Refresh GitHub Pages
        run: |
          # Create empty commit to trigger a rebuild
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit --allow-empty -m "Scheduled rebuild of GitHub Pages"
          git push